#!/bin/sh

set -e

cleanup()
{
        [ -z "$TEMP" ] || rm -f "$TEMP"
}

killall -w lighttpd

make clean
make bindir="${PWD}" runstatedir="${PWD}" pkgdatadir="${PWD}/htdocs" serverport=8080

TEMP=`mktemp` || {
        echo "Fatal: Could not create temporary file."
        exit 1
}

trap cleanup EXIT

cat > ${TEMP} << EOF
server.document-root = "/dev/null"
server.port = 8080
include "${PWD}/lighttpd.conf"
EOF

env -i PATH="${PATH}:${PWD}" lighttpd -f ${TEMP}
