Content-Type: text/html;charset=utf-8
<% source ./environment.inc %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
 <head>
  <title>Dreambox <% printf $product %> - <% printf $page_title %></title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
  <style type="text/css">
   @import url("second.css");
  </style>
 </head>
 <body>
